// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-peO1MulCaEaOx7C_-71ZoN-r9IZSoY',
    appId: '1:374714244402:web:1800ccd11e9851e9ce8b2b',
    messagingSenderId: '374714244402',
    projectId: 'client-digcoach',
    authDomain: 'client-digcoach.firebaseapp.com',
    storageBucket: 'client-digcoach.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSziRTUSUuZeu2l0DbAOY60RXVJ78OXUU',
    appId: '1:374714244402:android:c3cf73438893b390ce8b2b',
    messagingSenderId: '374714244402',
    projectId: 'client-digcoach',
    storageBucket: 'client-digcoach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkRir2cvVh9vc--PHkFNLgOxgIFZD1zHQ',
    appId: '1:374714244402:ios:ed6407faff7cb9c9ce8b2b',
    messagingSenderId: '374714244402',
    projectId: 'client-digcoach',
    storageBucket: 'client-digcoach.appspot.com',
    iosClientId: '374714244402-dg9lhgtm7pbjn99o7vni0ibr0b3jdoiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientsDigcoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkRir2cvVh9vc--PHkFNLgOxgIFZD1zHQ',
    appId: '1:374714244402:ios:ed6407faff7cb9c9ce8b2b',
    messagingSenderId: '374714244402',
    projectId: 'client-digcoach',
    storageBucket: 'client-digcoach.appspot.com',
    iosClientId: '374714244402-dg9lhgtm7pbjn99o7vni0ibr0b3jdoiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientsDigcoach',
  );
}
